### ISSUE TITLE
Procurement check stock first - nothing happens

### ISSUE THREAD

**Issue by anhdv1979** [FalinwaLimited/falinwa_branch#2]
Dear Sir/Madam,
Thanks for your modules. However, after installing your module (with check stock), I see nothing happen.
I have a situation. I make a sale order of 1 product (with multi-nested BOM) with quantity (10) and in stock is 5, it still generates MO with 10 quantity.
I would like it works as:
1. Check the quantity of product in stock -> generates MO with the sale - real and the same with the multiple level BOM of this product.
Pls help me. Many thanks for your help!
(P.S: I used multi company)

**Comment by falinwa** [comment]
have you configure the route for make to order?
You must check the check stock checkbox on that route.

**Comment by anhdv1979** [comment]
Many thanks for your help!
